#Image to pull from
FROM python:3.7-slim as builder

#Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

#Set work directory
WORKDIR /code

#install netcat
RUN apt-get update && apt-get install -y netcat

#Install dependencies
RUN pip install --upgrade pip
COPY Pipfile Pipfile.lock /code/
RUN pip install pipenv && pip install flake8 && pipenv install --system

#Copy project
COPY . /code/
RUN flake8 --ignore=E501,F401 .

#copy entrypoint.sh
COPY ./entrypoint.sh .

#update the permission
#RUN chmod +x /code/entrypoint.sh

#########
# FINAL #
#########

#pull official base image
FROM python:3.7-slim

#create directory for the app user
RUN mkdir -p /home/code

#create the app user
RUN addgroup -S app && adduser -S app -G app

#create appropriate diretories
ENV HOME=/home/code
ENV APP_HOME=/home/code/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

#install dependancies
RUN apk update && apk add libpq
COPY --from=builder /code/wheels /wheels
COPY --from=builder /code/


#run entrypoint.sh
ENTRYPOINT ["/code/entrypoint.sh"]